<title>Oz | Freelance Web Developer</title>
	<link rel="stylesheet" href="http://localhost/projects/oz.me/assets/css/style.css"/>
	<script src="http://localhost/projects/oz.me/assets/js/jquery.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<link href="http://localhost/projects/oz.me/assets/font/englebert.css" rel="stylesheet">
	<link href="http://localhost/projects/oz.me/assets/font/hind.css" rel="stylesheet">
	<link rel="stylesheet" href="http://localhost/projects/oz.me/assets/font-awesome-4.7.0/css/font-awesome.min.css">