<div id="sdbar">
	<div id="rst-cls"></div>
	<div id="mnu">
		<div class="m-icon"><span class="fa fa-times"></span></div>
		<div id="mnu-cnt">
			<a href="http://localhost/projects/oz.me">Home</a>
			<a href="http://localhost/projects/oz.me/hire-oz/">Hire me</a>
			<a href="http://localhost/projects/oz.me/portfolio/">More Portfolio</a>
			<a href="http://localhost/projects/oz.me/story-me/">My Story</a>
		</div>
	</div>
</div>
